// Single source for every campaign and transactional email (brief §9, §10).
// Merge tags ({{...}}) are resolved at send time; the dispatcher refuses any message with unresolved tags.
// Subject variants: index 0 is the lead test; all are candidates for A/B/n testing.
// The 'last email' subject is used ONLY on the final-hours note, which is the true last campaign email.
// Block types: string paragraph | {cta} | {list} | {sig} | {note} | {prep: 'planned'|'approved', text}

const SIG_FULL = { sig: ['The RSD Team', 'Real Social Dynamics'] };
const SIG = { sig: ['The RSD Team'] };
const u = (path) => `{{siteUrl}}${path}?utm_source=email&utm_campaign=rsd-is-back-2026`;

export const EMAILS = [
  {
    id: 'day01-reintroduction', kind: 'marketing', dayOffset: 0, segments: ['A', 'B', 'C', 'D', 'E', 'F'],
    subjects: ['RSD is back. Here\'s what you missed.', 'The RSD prequel is opening', 'You know one chapter. Explore the earlier ones.', 'The original RSD archive is open', 'Nearly 20 years of RSD training just reopened'],
    preheader: 'A 14-day archive release, with two package-only launch bonuses.',
    blocks: [
      'Hi {{firstNameOrThere}},',
      'If you came to RSD through Julien\'s later transformation work or another personal-growth program, you may know one part of the story.',
      'RSD is back.',
      'You\'ve seen the sequel. Real Social Dynamics has the prequel.',
      'Dating-focused teaching. Social situations. Communication. Different instructors explaining how they approached putting ideas into practice.',
      'We are bringing those chapters together in the RSD Legacy Archive: The Prequel Collection.',
      'This is not an invitation to copy someone else\'s personality. It is an opportunity to study the earlier work, compare perspectives, and decide what belongs in your own next chapter.',
      'During the 14-day return promotion, the $997 package includes the listed archive plus one live RSD Success Coaching Call and an invitation to a private package-holder RSD Nation relaunch briefing.',
      { cta: { label: 'EXPLORE THE PREQUEL COLLECTION', url: u('/') } },
      'Already own part of it? Check your existing access before purchasing again. Trouble with an old order? Reply for support, call RSD Support at 310-202-9002, or email support@realsocialdynamics.com; another purchase is not required.',
      SIG_FULL,
      { note: 'The recordings are archival. They do not imply current participation by Julien or other original instructors. Future bootcamps and tour events are separate purchases.' },
    ],
  },
  {
    id: 'day03-prequel-story', kind: 'marketing', dayOffset: 2, segments: ['A', 'B', 'C', 'D', 'E', 'F'],
    subjects: ['You saw the sequel. Want to see the prequel?', 'What Julien was teaching before the transformation era', 'The training before the transformation', 'The earlier chapters behind familiar ideas'],
    preheader: 'PIMP, SHIFT, and TenGame are different programs with different emphases.',
    requiresJulienSequence: true,
    blocks: [
      'Hi {{firstNameOrThere}},',
      'An idea can feel clear when you are watching a lesson and much less clear when you are in a conversation.',
      'That gap is part of what makes an archive worth studying.',
      'PIMP provides an earlier dating-focused reference point. SHIFT discusses identity, beliefs, and experience. TenGame supplies a principle-and-practice perspective.',
      'The point is not that the earliest method was perfect, or that one teacher had every answer.',
      'The point is context.',
      'You can examine the differences, keep what is appropriate and useful, and bring better questions to your included RSD Success Coaching Call.',
      { cta: { label: 'SEE THE JULIEN PREQUEL CHAPTERS', url: u('/legacy#julien-prequel') } },
      'The launch package is $997, including both package-only bonuses until {{launchEndLocal}}. Existing course access remains separate from this offer.',
      SIG,
    ],
  },
  {
    id: 'day05-beyond-one-role-model', kind: 'marketing', dayOffset: 4, segments: ['A', 'B', 'C', 'D', 'E', 'F'],
    subjects: ['Don\'t copy your role models. Study them.', 'Why we brought the old RSD programs back', 'Some of this training is 15+ years old. Good.', 'Study the approach, not just the personality'],
    preheader: 'Compare how the archive approaches communication and social life.',
    blocks: [
      'Hi {{firstNameOrThere}},',
      'When an instructor\'s work resonates, it can be tempting to copy how they sound.',
      'I would rather you study what they were trying to explain.',
      'The archive gives you different lenses: the early RSD classics, Resonator\'s communication focus, social-circle material, and other verified instructor collections.',
      'Compare the approaches. Notice what disagrees. Ask what suits your goals and what needs to be reconsidered in today\'s context.',
      'A role model can give you a reference point. Your life still needs your judgment.',
      { cta: { label: 'EXPLORE THE INSTRUCTOR COLLECTIONS', url: u('/legacy') } },
      'The full launch package includes the listed archive, one live success call, and your package-holder RSD Nation briefing invitation. Individual purchases do not include those launch bonuses.',
      SIG,
    ],
  },
  {
    id: 'day07-bonus-success-call', kind: 'marketing', dayOffset: 6, segments: ['A', 'B', 'C', 'D', 'E', 'F'],
    subjects: ['Nearly 20 years of material. Where do you start?', 'Your RSD Success Coach is included', 'Your archive purchase includes a live success call'],
    preheader: 'A current RSD Success Coach helps you plan a practical starting point.',
    blocks: [
      'Hi {{firstNameOrThere}},',
      'A broad library creates a simple question: where do I begin?',
      'That is why this launch package includes one complimentary live RSD Success Coaching Call.',
      'Discuss your goals. Identify the relevant programs. Outline an initial study-and-practice plan. Ask how the published preparation path relates to future RSD-operated live training.',
      'The call is with a current RSD Success Coach, not a promised session with Julien or another historical instructor. It requires no further purchase.',
      { cta: { label: 'UNLOCK THE ARCHIVE + SUCCESS CALL', url: u('/#package') } },
      'The package also includes the private RSD Nation relaunch-briefing invitation. Both bonuses are exclusive to qualifying package purchases during this promotion.',
      '{{approvedCallTermsShort}}',
      SIG,
    ],
  },
  {
    id: 'day09-bonus-rsd-nation', kind: 'marketing', dayOffset: 8, segments: ['A', 'B', 'C', 'D', 'E', 'F'],
    subjects: ['The videos are only the beginning', 'What comes after the archive', 'Your package-holder invitation to the RSD Nation briefing'],
    preheader: 'Hear the next-chapter plans through the package-only briefing invitation.',
    blocks: [
      'Hi {{firstNameOrThere}},',
      'The archive looks back. The RSD Nation relaunch briefing looks ahead.',
      'Qualifying launch-package buyers receive an invitation to the private package-holder briefing as the second included bonus.',
      'We plan to reconnect the community and explain the next RSD chapter, including planned bootcamps and other live programs as the details are confirmed.',
      'This is an invitation to the specified briefing, not free entry to a global tour, a bootcamp reservation, or a promise that the original instructors will attend.',
      { cta: { label: 'VIEW THE PACKAGE + BOTH BONUSES', url: u('/#package') } },
      '{{approvedBriefingTermsShort}}',
      'The archive, success call, and briefing invitation are $997 together during the promotion. Individual courses do not include these two bonuses.',
      SIG,
    ],
  },
  {
    id: 'day11-preparation', kind: 'marketing', dayOffset: 10, segments: ['A', 'B', 'C', 'D', 'E', 'F'],
    subjects: ['Study before you arrive. Show up ready to work.', 'Before the bootcamp, build the foundation', 'A starting path, not an endless video checklist'],
    preheader: 'How the archive is intended to connect to future live training.',
    blocks: [
      'Hi {{firstNameOrThere}},',
      'We do not want preparation for live training to mean watching every video ever made.',
      { prep: 'approved', text: 'For designated future RSD-operated programs, the published Foundations Path will identify the lessons and preparation that must be completed before attending.' },
      { prep: 'approved', text: 'The relevant archive lessons are included in this package. Existing valid owners can satisfy the requirement without purchasing the same lessons again.' },
      { prep: 'planned', text: 'We are developing a preparation path to help customers connect archive study with future RSD live programs. Applicable requirements will be published alongside those programs.' },
      'The goal is to arrive with useful context and questions, not just a receipt.',
      'Cities, dates, coaches, admission, and tuition for planned global-tour programs will be announced separately. Buying the archive does not reserve a place.',
      { cta: { label: 'EXPLORE THE ARCHIVE AND PREPARATION PATH', url: u('/preparation') } },
      'The two package-only bonuses remain included through {{launchEndLocal}}.',
      SIG,
    ],
  },
  {
    id: 'day13-48-hour-notice', kind: 'marketing', sendAt: 'deadline-minus-48h', segments: ['A', 'B', 'C', 'D', 'E', 'F'],
    subjects: ['48 hours left', '48 hours left on the RSD archive launch offer', 'The package bonuses close with the launch offer'],
    preheader: 'The real deadline is {{launchEndLocal}}.',
    blocks: [
      'Hi {{firstNameOrThere}},',
      { variantOnly: 'enrolledDay1', text: 'You\'ve had 12 days. Now there are 48 hours left.' },
      'The RSD return promotion ends in 48 hours, at {{launchEndLocal}}.',
      'Until then, the $997 package includes:',
      { list: ['The specific RSD legacy programs and editions listed on the offer page.', 'One complimentary live Success Coaching Call with a current RSD Success Coach.', 'The exclusive package-holder RSD Nation relaunch-briefing invitation.'] },
      'Check the catalog and your existing access before deciding. The reason to buy is the material and benefits you want, not a claim that you need to become someone else.',
      { cta: { label: 'REVIEW THE PACKAGE BEFORE THE DEADLINE', url: u('/#package') } },
      'After the deadline, {{approvedPostLaunchChange}}. We will not reset this countdown for returning visitors.',
      SIG,
    ],
  },
  {
    id: 'day14-final-day', kind: 'marketing', sendAt: 'deadline-day-morning', segments: ['A', 'B', 'C', 'D', 'E', 'F'],
    subjects: ['Tonight, the RSD return special ends', 'Final day: the RSD prequel package', 'The 14-day RSD return special ends tonight'],
    preheader: 'Archive + success call + package-holder briefing invitation.',
    blocks: [
      'Hi {{firstNameOrThere}},',
      'Tonight the $997 Complete Archive launch offer and its two launch bonuses end.',
      'Today is the final day of the RSD Legacy Archive return promotion. RSD is back, and this is the last day of the launch offer.',
      'You may already know the later personal-growth chapter. This collection lets you explore earlier dating and communication material, compare instructors, and choose a path through the archive.',
      'The qualifying package also includes the live success call and private RSD Nation relaunch-briefing invitation.',
      '$997 one-time. Offer ends {{launchEndLocal}}.',
      { cta: { label: 'UNLOCK THE ARCHIVE + BOTH BONUSES', url: u('/#package') } },
      'Bootcamps and future tour programs are sold separately. The recordings do not imply current instructor participation. Need help with an earlier purchase? Use support instead of buying it again.',
      SIG_FULL,
    ],
  },
  {
    id: 'final-hours-optional', kind: 'marketing', sendAt: 'deadline-minus-6h', segments: ['A', 'B', 'C', 'D', 'E', 'F'], engagedOnly: true,
    subjects: ['This is the last email I\'ll send you about the RSD return special', 'Final hours: the RSD archive return offer'],
    preheader: 'The launch price and both package-only bonuses end at {{launchEndLocal}}.',
    blocks: [
      'Hi {{firstNameOrThere}},',
      'This is the last email I\'ll send you about the RSD return special. The 14-day offer ends at {{launchEndLocal}}.',
      'The listed RSD Legacy Archive, one live success call, and your private RSD Nation briefing invitation are $997 together during this window.',
      { cta: { label: 'REVIEW THE OFFER', url: u('/#package') } },
      'After the deadline, {{approvedPostLaunchChange}}.',
      'Thanks for being part of the conversation, whether you join this release or not.',
      SIG,
    ],
  },
  {
    id: 'dormant-reintroduction', kind: 'marketing', dayOffset: 0, segments: ['I'],
    subjects: ['Would the RSD archive be relevant to you?'],
    preheader: 'An invitation from Real Social Dynamics, with a choice about future updates.',
    blocks: [
      'Hi {{firstNameOrThere}},',
      'You previously connected with Real Social Dynamics. We are preparing a 14-day release of historical Real Social Dynamics training, focused on the earlier dating, communication, and personal-development chapters.',
      'If that interests you, you can explore the preview and choose whether to receive this campaign\'s updates.',
      { cta: { label: 'EXPLORE THE PREVIEW', url: u('/') } },
      { cta: { label: 'UPDATE MY EMAIL PREFERENCES', url: '{{preferencesURL}}', secondary: true } },
      'No interest? You can unsubscribe below. An existing purchase remains yours under its original terms regardless of your marketing preferences.',
      { sig: ['The RSD Team', 'Real Social Dynamics'] },
    ],
  },
  // ---- Transactional (sent regardless of marketing consent; never used to carry marketing) ----
  {
    id: 'txn-order-confirmation', kind: 'transactional', trigger: 'package_entitlement_created',
    subjects: ['Your RSD archive access and included launch benefits'], preheader: 'Order {{orderNumber}}: library, coaching call and briefing invitation.',
    blocks: [
      'Hi {{firstNameOrThere}},',
      'Thank you for purchasing {{packageName}}. Your order is {{orderNumber}}.',
      'Your included programs and exact editions: {{purchasedManifestSummary}}.',
      { cta: { label: 'OPEN MY LIBRARY', url: '{{secureLibraryURL}}' } },
      'Book your included RSD Success Coaching Call: {{secureBookingURL}}',
      'View your private RSD Nation briefing invitation: {{secureInvitationURL}}',
      '{{approvedCallTerms}}',
      '{{approvedBriefingTerms}}',
      'Your receipt and access terms: {{receiptURL}}',
      'Questions about an earlier purchase or this order? {{supportContact}}',
      { note: 'This purchase does not include bootcamp tuition, global-tour tickets, travel, or accommodation. Your coaching session is provided by the current RSD team, not a promised historical instructor.' },
    ],
  },
  {
    id: 'txn-success-call-booking', kind: 'transactional', trigger: 'bonus:success-call granted',
    subjects: ['Book your included RSD Success Coaching Call'], preheader: 'One live call with a current RSD Success Coach, included with your package.',
    blocks: [
      'Hi {{firstNameOrThere}},',
      'Your launch package includes one live RSD Success Coaching Call with a current RSD Success Coach.',
      'Use it to talk through what you want to work on, identify the most relevant lessons in your library, and outline a practical first step.',
      { cta: { label: 'BOOK MY CALL', url: '{{secureBookingURL}}' } },
      '{{approvedCallTerms}}',
      'This is educational coaching, not therapy, and no further purchase is required. {{optionalProgramsDisclosure}}',
      'Need to reschedule or having trouble booking? {{supportContact}}',
    ],
  },
  {
    id: 'txn-briefing-invitation', kind: 'transactional', trigger: 'bonus:briefing-invite granted',
    subjects: ['Your private RSD Nation relaunch-briefing invitation'], preheader: 'Package-holder briefing: {{briefingDateAndTime}}.',
    blocks: [
      'Hi {{firstNameOrThere}},',
      'As a launch-package holder, you are invited to the private RSD Nation relaunch briefing.',
      { list: ['When: {{briefingDateAndTime}}', 'Format: {{briefingFormat}}', 'Hosts: {{confirmedHosts}}'] },
      { cta: { label: 'VIEW MY INVITATION', url: '{{secureInvitationURL}}' } },
      'This invitation is personal to your order. It is not a bootcamp reservation, a global-tour ticket, or a change to ordinary RSD Nation access.',
      '{{briefingDeliveryCommitment}}',
    ],
  },
];

export const FOOTER = {
  lines: [
    '{{actualSenderLegalName}}',
    '{{currentValidPostalAddress}}',
    'You are receiving this promotional message because {{verifiedSubscriptionExplanation}}.',
  ],
  links: [['Manage preferences', '{{preferencesURL}}'], ['Unsubscribe', '{{unsubscribeURL}}'], ['Help with an existing purchase', '{{supportURL}}']],
  phone: 'RSD Support: 310-202-9002 · support@realsocialdynamics.com',
  disclosure: 'This is an RSD archive promotion sent by the identified sender. Historical course attribution does not imply current participation or endorsement by the original instructor. The free success call and private briefing invitation are conditional on the qualifying package purchase and the published terms.',
};
